### ISSUE TITLE
update version deployed by helm / kubectl

### ISSUE THREAD

**Issue by agup006** [calyptia/charts#32]
The version installed by helm / kubectl is 0.4.2, can we add GH action to ensure it is the latest?

@niedbalski @patrick-stephens ?

**Comment by patrick-stephens** [comment]
I'll update the existing release workflow to make sure it provides the latest as well.

**Comment by patrick-stephens** [comment]
Ah, this was already provided gents - it just wasn't in the right directory!
https://github.com/calyptia/charts/blob/2e3aa680d2f9fc6d8f6ab994718fd02c213aec73/.github/cron-sync-core.yaml

This will test for new releases and update Chart Version with PRs. Same as for lots of other stuff.
