### ISSUE TITLE
Resolve release failure

### ISSUE THREAD

**Issue by patrick-stephens** [calyptia/charts#41]
Automation updated only appVersion: https://github.com/calyptia/charts/actions/runs/4499098643

**Comment by vigneshcommits** [comment]
PRs:
https://github.com/calyptia/charts/pull/45/files
https://github.com/calyptia/core-images/pull/233/files

**Comment by patrick-stephens** [comment]
@vigneshcommits please add the "Resolves X" where X is the issue number to PRs in future so they are auto-closed.
